title: 嗨嗨, 我是鳗鱼!
description: # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/louisopen.github.io" # the subpath of your site, e.g. /blog
url: "https://louisopen.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: 鳗鱼 # add your name
author-img: chick-freeman.jpg #add your photo
about-author: I am a old coding farmer focusing on Assembly,C-like,C,RTOS,C#,UWP,Windows iot,RaspBian Linux,Python program development. Now,I want to link all the code and code to clouds base on my 8bit/16bit/32bit MCU,Arduino,Raspberry Pi,Jetson nano. That is my interest outside of work.  # add description
social-twitter: louisopen # add your Twitter handle
social-facebook: louisopen@gmail.com # add your Facebook handle
social-github: louisopen # add your Github handle
social-linkedin: louisopen@gmail.com # add your Linkedin handle
social-email: louisopen@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
